test:
  imports:
    - typecheck_runner
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wpk-nist-gov/typecheck-runner
  summary: Unified api to multiple typecheckers
  description: |
    Unified api to multiple typecheckers
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
